name: Playing with workflows

on:
  push:
    branches:
      - master
    paths:
      - "src/*"
      - ".github/workflows/Play.yml"

jobs:
  play:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: list
        run: ls
   
      